version: '3.8'

services:
  app:
    build: .
    image: ideogram-api-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/ideogram-api
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
      - IDEOGRAM_API_KEY=${IDEOGRAM_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
    volumes:
      - ./logs:/usr/src/app/logs
    depends_on:
      - mongodb
      - redis
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  mongodb_data:
  redis_data: 